name: Homebrew bump formula
description: Bump (update) a Homebrew formula on new project release
author: dawidd6
branding:
  icon: arrow-up-circle
  color: yellow
inputs:
  token:
    description: Github token (not the default one)
    required: true
  formula:
    description: |
      Formula name

      Optionally in format USER/REPO/FORMULA

      Example: lazygit
      Example: dawidd6/tap/actions-updater
    required: true
  tag:
    description: |
      Git tag

      Example: v1.0.0
      Example: refs/tags/v1.0.0
    required: false
    default: ${{github.ref}}
  revision:
    description: |
      Git revision

      Only required for formulae that use git to download the source

      Example: 130d3a3af72f66780ae4e24cd143ae7a4d757f9d
    required: false
    default: ${{github.sha}}
  force:
    description: Check open PRs or not (will fail if detected)
    required: false
runs:
  using: docker
  image: Dockerfile
