name: Test Action

on:
  push:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        formula:
          - test-formula-url
          - test-formula-git-revision
        include:
          - formula: test-formula-url
            os: macos-latest
            tap: dawidd6/test
            tag: v0.1.12
            force: false
          - formula: test-formula-git-revision
            os: ubuntu-latest
            tap: dawidd6/test
            tag: v0.3.3
            revision: c43abd765cf51c06bbcaa5479dc49aab1396989f
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        uses: ./
        with:
          token: ${{secrets.TOKEN}}
          tap: ${{matrix.tap}}
          formula: ${{matrix.formula}}
          tag: ${{matrix.tag}}
          revision: ${{matrix.revision}}
          force: ${{matrix.force}}
